/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nyabsino[KMM]™ (https://sketchfab.com/nyabsino)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-basic-campus-scene-7a2adf11dadf48289a7ee82692b43965
Title: [FREE] Basic Campus: Scene
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function AboutCollage(props) {
  const { nodes, materials } = useGLTF('/models/NewModels/compressed_Building.glb')
  return (
    <group {...props} dispose={null} position={[-4.859, 0.459, -52.209]} scale={1.031}> 
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.JKT_MTP_61003_JKT_MTP_61_0.geometry}
        material={materials['Material.005']}
        // position={[-4.836, 0.449, -52.115]}
        rotation={[-Math.PI / 2, 0, -0.66]}
        scale={0.031}
      />
      {/* <axesHelper args={[10000]} /> */}
    </group>
  )
}

useGLTF.preload('/models/NewModels/compressed_Building.glb')


