/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function AnimatedBook(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/NewModels/bookanimation.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Play all available animations with slower speed
    if (actions) {
      Object.values(actions).forEach((action) => {
        if (action) {
          action.reset()
          action.timeScale = 0.3 // Make animation 30% of original speed (slower)
          action.play()
        }
      })
    }
  }, [actions])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -1]} position={[7.119, 0.431, -59.817]} scale={0.209}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="cover-l_36"
                position={[0.09, 0.205, 0]}
                rotation={[0, 0, -Math.PI]}
                scale={[0.71, 0.025, 1]}>
                <mesh
                  name="Object_8"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_8.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="cover-r_35" position={[0.09, 0.025, 0]} scale={[0.71, 0.025, 1]}>
                <mesh
                  name="Object_6"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_6.geometry}
                  material={materials['Material.004']}
                />
              </group>
              <group
                name="paper001_40"
                position={[0.09, 0.035, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_12"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_12.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper002_41"
                position={[0.09, 0.04, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_14"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_14.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper003_42"
                position={[0.09, 0.045, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_16"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_16.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper004_43"
                position={[0.09, 0.05, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_18"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_18.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper005_44"
                position={[0.09, 0.056, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_20"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_20.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper006_45"
                position={[0.09, 0.061, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_22"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_22.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper007_46"
                position={[0.09, 0.066, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_24"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_24.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper008_47"
                position={[0.09, 0.071, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_26"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_26.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper009_48"
                position={[0.09, 0.076, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_28"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_28.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper010_49"
                position={[0.09, 0.081, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_30"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_30.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper011_50"
                position={[0.09, 0.086, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_32"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_32.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper012_51"
                position={[0.09, 0.091, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_34"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_34.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper013_52"
                position={[0.09, 0.096, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_36"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_36.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper014_53"
                position={[0.09, 0.102, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_38"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_38.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper015_54"
                position={[0.09, 0.107, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_40"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_40.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper016_55"
                position={[0.09, 0.112, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_42"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_42.geometry}
                  material={materials['Material.005']}
                />
              </group>
              <group
                name="paper017_56"
                position={[0.09, 0.117, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_44"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_44.geometry}
                  material={materials['Material.006']}
                />
              </group>
              <group
                name="paper018_57"
                position={[0.09, 0.122, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_46"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_46.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper019_58"
                position={[0.09, 0.127, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_48"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_48.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper020_59"
                position={[0.09, 0.132, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_50"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_50.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper021_60"
                position={[0.09, 0.137, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_52"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_52.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper022_61"
                position={[0.09, 0.142, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_54"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_54.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper023_62"
                position={[0.09, 0.148, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_56"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_56.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper024_63"
                position={[0.09, 0.153, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_58"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_58.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper025_64"
                position={[0.09, 0.158, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_60"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_60.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper026_65"
                position={[0.09, 0.163, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_62"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_62.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper027_66"
                position={[0.09, 0.168, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_64"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_64.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper028_67"
                position={[0.09, 0.173, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_66"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_66.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper029_68"
                position={[0.09, 0.178, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_68"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_68.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper030_69"
                position={[0.09, 0.183, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_70"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_70.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper031_70"
                position={[0.09, 0.188, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_72"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_72.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper032_71"
                position={[0.09, 0.194, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_74"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_74.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper033_72"
                position={[0.088, 0.196, 0]}
                rotation={[Math.PI / 2, 0.01, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_76"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_76.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="paper_39"
                position={[0.09, 0.03, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.71, 1, 1]}>
                <mesh
                  name="Object_10"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_10.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group
                name="pine_34"
                position={[0.065, 0.115, 0]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.09, 0.025, 1]}>
                <mesh
                  name="Object_4"
                  castShadow={false}
                  receiveShadow={false}
                  geometry={nodes.Object_4.geometry}
                  material={materials['Material.003']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bookanimation.glb')

