/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Books(props) {
  const { nodes, materials } = useGLTF('/models/NewModels/compressed_books.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[7.019, 0.441, -60.417]} scale={0.129}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_0.geometry}
          material={materials.Books}
          position={[0.438, -0.194, 1.669]}
          rotation={[-Math.PI / 2, -1.498, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_0.geometry}
          material={materials.Books}
          position={[0.438, -0.159, 0.189]}
          rotation={[-Math.PI / 2, -1.504, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_0.geometry}
          material={materials.Books}
          position={[0.498, -0.098, 0.586]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_0.geometry}
          material={materials.Books}
          position={[0.567, 0, 1.954]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_0.geometry}
          material={materials.Books}
          position={[0.347, 0.052, 1.365]}
          rotation={[Math.PI / 2, -1.508, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_0.geometry}
          material={materials.Books}
          position={[0.438, 0.185, 0.972]}
          rotation={[Math.PI / 2, -1.493, Math.PI / 2]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/NewModels/compressed_books.glb')


