/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function ContactModel(props) {
  const { nodes, materials } = useGLTF('/models/NewModels/Phone.glb')
  const meshRef = useRef()

  useFrame((state, delta) => {
    if (meshRef.current) {
      meshRef.current.rotation.y += delta * 0.5 // Adjust speed by changing the multiplier
    }
  })

  return (
    <group {...props} dispose={null} position={[4.690, 0.341, -51.837]}>
      <mesh
        ref={meshRef}
        castShadow
        receiveShadow
        geometry={nodes.Pixel_7_Pro.geometry}
        material={materials['Material.002']}
        position={[-0.03, 0.822, -0.022]}
        rotation={[Math.PI, -0.564, Math.PI]}
        scale={1.769}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lens_glass_0.geometry}
        material={materials['glass.001']}
        position={[-0.061, 0.149, -0.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Cylinder008_13_-_Default_0'].geometry}
        material={materials['13_-_Default']}
        position={[-0.032, 0.395, -0.015]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.008, 0.007, 0.011]}
      />
      <group position={[-0.061, 0.149, -0.125]} rotation={[-Math.PI / 2, 0, 0]} scale={0.013}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box009_blue_dongle_0_1.geometry}
          material={materials.blue_dongle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box009_blue_dongle_0_2.geometry}
          material={materials.basematerial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box009_blue_dongle_0_3.geometry}
          material={materials.heatshield}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box009_blue_dongle_0_4.geometry}
          material={materials.bridge}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box009_blue_dongle_0_5.geometry}
          material={materials.blocks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box009_blue_dongle_0_6.geometry}
          material={materials.backmetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box009_blue_dongle_0_7.geometry}
          material={materials.dongles}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box009_blue_dongle_0_8.geometry}
          material={materials.pipes}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/NewModels/Phone.glb')


