/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ContactPhone(props) {
  const { nodes, materials } = useGLTF('/models/NewModels/compressed_Pixel 7 Pro.glb')
  return (
    <group {...props} dispose={null} position={[3.890, 1.141, -51.737]} scale={3.501} rotation={[0, 3.610, 0.223]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Pixel 7 Pro.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_1.geometry}
        material={materials['Pixel 7 Pro']}
      />
    </group> 
  )
}

useGLTF.preload('/models/NewModels/compressed_Pixel 7 Pro.glb')



