/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pen(props) {
  const { nodes, materials } = useGLTF('/models/NewModels/compressed_pen.glb')
  return (
    <group {...props} dispose={null} position={[7.219, 0.431, -59.217]} scale={1.901} rotation={[0, 1, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Material.001']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/NewModels/compressed_pen.glb')



