/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Router(props) {
  const { nodes, materials } = useGLTF('/models/NewModels/scifirouter.glb')
  return (
    <group {...props} dispose={null} position={[3.890, 0.441, -51.737]} scale={0.0412}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Antennas_4.geometry}
        material={materials.Antennas_4}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Back_Plate_18.geometry}
        material={materials.Back_Plate_18}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Back_Plate_9.geometry}
        material={materials.Back_Plate_9}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Case.geometry}
        material={materials.Case}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Connectors_.geometry}
        material={materials.Connectors_}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ethernet_Covers.geometry}
        material={materials.Ethernet_Covers}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Face_Plate.geometry}
        material={materials.Face_Plate}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Green_LED.geometry}
        material={materials.Green_LED}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pronges.geometry}
        material={materials.Pronges}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Socket.geometry}
        material={materials.Socket}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Switch.geometry}
        material={materials.Switch}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Yellow_LED.geometry}
        material={materials.Yellow_LED}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/NewModels/scifirouter.glb')


