/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function StartupTn(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/NewModels/compressed_1753687805860_startupTN.glb')
  const { actions } = useAnimations(animations, group)
  
  useEffect(() => {
    // Play all available animations
    Object.values(actions).forEach((action) => {
      action?.play()
    })
  }, [actions])
  
  return (
    <group ref={group} {...props} dispose={null} position={[-0.100, 1.176, -63.157]} scale={0.1112}>
      <group name="Scene">
        <group name="RootNode" scale={0.001}>
          <group
            name="Arrow"
            position={[143.983, 278.053, -192.014]}
            rotation={[-Math.PI / 2, -Math.PI / 9, 0]}
            scale={4}>
            <mesh
              name="Arrow_Arrow_0"
              castShadow
              receiveShadow
              geometry={nodes.Arrow_Arrow_0.geometry}
              material={materials.Arrow}
            />
          </group>
        </group>
        <group
          name="Coins"
          position={[0.007, 4.507, -1.43]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.01}>
          <group
            name="Coin_01"
            position={[53.483, -225.959, -46.332]}
            rotation={[-1.116, 1.079, 1.877]}>
            <mesh
              name="Coin_01_Coin_0"
              castShadow
              receiveShadow
              geometry={nodes.Coin_01_Coin_0.geometry}
              material={materials.Coin}
            />
          </group>
          <group
            name="Coin_02"
            position={[307.853, -210.091, -107.652]}
            rotation={[-2.053, 0.299, 2.975]}>
            <mesh
              name="Coin_02_Coin_0"
              castShadow
              receiveShadow
              geometry={nodes.Coin_02_Coin_0.geometry}
              material={materials.Coin}
            />
          </group>
          <group
            name="Coin_03"
            position={[-288.654, 215.979, -424.283]}
            rotation={[-2.174, 0.753, 2.309]}>
            <mesh
              name="Coin_03_Coin_0"
              castShadow
              receiveShadow
              geometry={nodes.Coin_03_Coin_0.geometry}
              material={materials.Coin}
            />
          </group>
          <group
            name="Coin_04"
            position={[200.324, 249.535, -425.153]}
            rotation={[-0.814, 1.443, 1.153]}>
            <mesh
              name="Coin_04_Coin_0"
              castShadow
              receiveShadow
              geometry={nodes.Coin_04_Coin_0.geometry}
              material={materials.Coin}
            />
          </group>
          <group
            name="Coin_05"
            position={[-12.502, -146.031, -427.099]}
            rotation={[-2.312, -0.953, 2.718]}>
            <mesh   
              name="Coin_05_Coin_0"
              castShadow
              receiveShadow
              geometry={nodes.Coin_05_Coin_0.geometry}
              material={materials.Coin}
            />
          </group>
          <group
            name="Coin_06"
            position={[159.27, -72.142, -142.153]}
            rotation={[-2.147, 0.153, 3.055]}>
            <mesh
              name="Coin_06_Coin_0"
              castShadow
              receiveShadow
              geometry={nodes.Coin_06_Coin_0.geometry}
              material={materials.Coin}
            />
          </group>
          <group
            name="Coin_07"
            position={[-91.143, 188.192, -192.289]}
            rotation={[1.513, 0.634, -1.563]}>
            <mesh
              name="Coin_07_Coin_0"
              castShadow
              receiveShadow
              geometry={nodes.Coin_07_Coin_0.geometry}
              material={materials.Coin}
            />
          </group>
        </group>
        <mesh
          name="CoinsGroup_CoinGroup_0"
          castShadow
          receiveShadow
          geometry={nodes.CoinsGroup_CoinGroup_0.geometry}
          material={materials.CoinGroup}
          position={[0.109, 0.043, -1.94]}
          scale={0.01}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/NewModels/compressed_1753687805860_startupTN.glb')

