/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WifiModel(props) {
  const { nodes, materials } = useGLTF('/models/NewModels/wifi.glb')
  return (
    <group {...props} dispose={null} position={[3.890, 1.541, -51.737]} scale={0.1012} rotation={[1, -0.234, 0.523]}> 
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Material.001']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/NewModels/wifi.glb')


