"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations,scene } = useGLTF('/Untitled.glb')
  const { actions,clips,names } = useAnimations(animations, group)

  console.log({actions,animations,clips,names});


  useEffect(() => {
    actions.Animation.play();
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
    <primitive object={scene} />
  </group>
  )
}

useGLTF.preload('/Untitled.glb')
