"use client";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/Components/Common/Nav/NavBar";
// import { StagewiseToolbar } from '@stagewise/toolbar-next';
// import { ReactPlugin } from '@stagewise-plugins/react';
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app", 
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-hidden" suppressHydrationWarning={true}>
          {/* <StagewiseToolbar config={{ plugins: [ReactPlugin] }} /> 
          <div className="w-full h-full bg-red-500">

          </div> */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
