/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function EntranceText(props) {
    const { nodes, materials } = useGLTF('/models/text_models/text robo room-opt.glb')
    const groupRef = useRef()


    return (
        <>
            <group {...props} dispose={null}  position={[-0.100, 0.076, -0.057]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text008_primitive0.geometry}
                    material={materials['Material.016']}
                    position={[4.277, 3.415, -28.004]}
                    rotation={[1.566, -0.001, 0.253]}
                    scale={1.084}
                />
            </group>
        </>
    )
}

useGLTF.preload('/models/text_models/text robo room-opt.glb')


